// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASTWV3Bw4Gyb-ekFU_Mk7JMagDVpv1VNw',
    appId: '1:986048658290:web:66f6df0fd860a1624bbbeb',
    messagingSenderId: '986048658290',
    projectId: 'evaluacion-b54c1',
    authDomain: 'evaluacion-b54c1.firebaseapp.com',
    databaseURL: 'https://evaluacion-b54c1-default-rtdb.firebaseio.com',
    storageBucket: 'evaluacion-b54c1.firebasestorage.app',
    measurementId: 'G-HEV9VRWLT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS5Qfjn4RQ6E-J4c2mkhtwW0k_5WnCzV8',
    appId: '1:986048658290:android:6eccf79dde5d69a64bbbeb',
    messagingSenderId: '986048658290',
    projectId: 'evaluacion-b54c1',
    databaseURL: 'https://evaluacion-b54c1-default-rtdb.firebaseio.com',
    storageBucket: 'evaluacion-b54c1.firebasestorage.app',
  );

}